spring:
  data:
    mongodb:
      uri: mongodb+srv://haomingjue:gng5300@cluster1.dhtfs7a.mongodb.net/gng5300?retryWrites=true&w=majority
      database: gng5300
  graphql:
      graphiql:
        enabled: true
server:
  port: 80
